### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-DuilioAquino10#2]
[Aquino Lopez Duilio Ruben - prac3.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-DuilioAquino10/files/6339736/Aquino.Lopez.Duilio.Ruben.-.prac3.pdf)

**Comment by Band-hi** [comment]
Practica 84/100
Calificación: 16.8

-Falta subir código a GitHub
-No tiene objetivo, material
-No contiene las 20 figuras mininas
-La conclusión no abarca 12 líneas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
